[package]
name = "wave_sim"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.36.2"
egui_plot = "0.37.0"
smart-default = "0.7.1"
web-time = "1.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Window", "Document", "Element"] }
log = "0.4"